### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by NicoGonzalez94** [lucaschipolari/milabar-frontend#65]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Encontrar el logo junto con el nombre de la pagina.

## Resultado actual

• Solo se encuentra el nombre sin el logo.

## Captura

![image](https://github.com/user-attachments/assets/19edb7b9-b931-4f62-b610-5980b63f11a4)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by lucaschipolari** [comment]
Hola nico, ahí le pusimos un logo a la pagina
![image](https://github.com/user-attachments/assets/e22dd851-696e-44e3-a0ea-48886fa5b526)
