### ISSUE TITLE
Menús vacíos

### ISSUE THREAD

**Issue by NicoGonzalez94** [lucaschipolari/milabar-frontend#66]
## Proceso

1. Ingrese a la pagina.

## Resultado esperado

• Encontrar al menos un producto en cada Menu.

## Resultado actual

• Los apartados de "Hamburguesas" y "Bebidas" se encuentran vacías.

## Captura

![image](https://github.com/user-attachments/assets/91211980-9cd1-4729-9daa-68a0e85cec94)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by lucaschipolari** [comment]
Hola nico, ahí rellené los menús que se encontraban vacíos
![image](https://github.com/user-attachments/assets/7c64cdea-ce64-4742-be52-f1911a1f1c6b)
