### ISSUE TITLE
Consola

### ISSUE THREAD

**Issue by NicoGonzalez94** [lucaschipolari/milabar-frontend#67]
## Proceso

1. Ingrese a la pagina.
2. Navegue por las diferentes secciones.

## Resultado esperado

• Que al cambiar de seccion no se muestre ningun error o mensaje por consola.

## Resultado actual

• Al navegar por las distintas secciones se muestra informacion por consola.

## Captura

[ [image]](https://github.com/user-attachments/assets/8740d6e7-a471-466b-961d-faea709b6c7b)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by lucaschipolari** [comment]
Hola nico, ahí solucionamos ese error, ahora no sale ninguna mensaje por consola, tampoco al cambiar de pagina.
![image](https://github.com/user-attachments/assets/b48046c7-cf5d-4fe4-b5d5-91501fab6a5e)
