### ISSUE TITLE
Contacto

### ISSUE THREAD

**Issue by NicoGonzalez94** [lucaschipolari/milabar-frontend#68]
## Proceso

1. Ingrese a la pagina.
2. Quise hacer una consulta.

## Resultado esperado

• Que al finalizar mi consulta no se muestre informacion por consola.

## Resultado actual

• Una vez enviada mi consulta se muestra informacion por consola. 

## Captura

![image](https://github.com/user-attachments/assets/6deef838-afe6-499c-aa94-bfdf78bfb715)

Cualquier cosita pueden contactarme a nicogonzalez2008@gmail.com o por el slack de RollingCode

**Comment by NicoGonzalez94** [comment]
Al momento de registrarse también se muestra informacion por consola.

![image](https://github.com/user-attachments/assets/c61a779a-174a-4e0d-a40a-a142f1d69e60)

![image](https://github.com/user-attachments/assets/dcd6e634-69ca-4385-b62b-73b03db60879)

**Comment by lucaschipolari** [comment]
![image](https://github.com/user-attachments/assets/ddf1e113-3681-4925-b279-fe04105a14bf)
![image](https://github.com/user-attachments/assets/c20087f7-923f-4efb-a3ea-9b3d443d132e)
![image](https://github.com/user-attachments/assets/ba44a71a-2794-4776-b156-32206ab212ce)
Se eliminaron los mensajes de consola
